# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Projecthub"
license = "MIT"
licenselink = "https://github.com/vjeantet/hugo-theme-projecthub/blob/master/LICENSE.md"
description = "An HTML template for project timelines"
homepage = "https://github.com/vjeantet/hugo-theme-projecthub/"
tags = ["projecthub", "timeline"]
features = ["", ""]
min_version = 0.13

[author]
  name = "Valere JEANTET"
  homepage = "http://vjeantet.fr"

# If porting an existing theme
[original]
  name = "Project Hub"
  homepage = "https://github.com/bradfrost/project-hub"
  repo = "https://github.com/bradfrost/project-hub"
