---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
BaseURL: "http://cloudnativejava.io"
title: "Cloud Native Java"
permalinks:
  - posts :  "/perma/:year/:month/:title/"
