---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseURL: "http://cloudnativejava.io"
title: "Cloud Native Java"
permalinks:
  post: /:year/:month/:title/
