name = "Hikari"
license = "MIT"
licenselink = "//github.com/digitalcraftsman/hugo-hikari-theme/blob/dev/LICENSE.MD"
description = " A minimal theme perfect for dev-savvy bloggers."
homepage = "//github.com/digitalcraftsman/hugo-hikari-theme"
tags = ["blog", "minimal", "syntax highlighting", "Disqus", "Google Analytics"]
features = ["", ""]
min_version = 0.14

[author]
  name = "digitalcraftsman"
  homepage = "//github.com/digitalcraftsman"

# If porting an existing theme
[original]
  name = "Mathieu Mayer-Mazzoli"
  homepage = "//mx3m.github.io"
  repo = "//github.com/mx3m/hikari-for-Jekyll"