languageCode = "en-us"
contentdir = "content"
publishdir = "public"
builddrafts = false
baseUrl = ""
canonifyurls = true


title = "Shiori"
author = "Shu Uesugi"

# [params]
#     author_name = "Shu Uesugi"
#     twitter_username = "chibicode"
#     gravatar_id = "d747ad92018acd87a77899704fc6693d"
