name = "Twenty Fourteen"
license = "GNU General Public License v2 or later"
licenselink = "http://www.gnu.org/licenses/gpl-2.0.html"
description = "A responsive magazine website with a sleek, modern design."
tags = ["blog", "wordpress"]
features = ["blog", ]
min_version = 0.14

[author]
    name = "Dan Hersam"
    homepage = "http://dan.hersam.com"

[original]
    author =  "wordpressdotorg"
    homepage = "https://wordpress.org/themes/twentyfourteen"
    repo = "https://themes.trac.wordpress.org/browser/twentyfourteen/1.3"
