name = "nofancy"
description = "a distraction-free hugo theme"
license = "MIT"
licenselink = "http://opensource.org/licenses/MIT"
homepage = "https://github.com/gizak/nofancy"
tags = ["blog", "personal"]
features = ["distraction-free","black-and-white"]
min_version=0.14

[author]
    name = "Zack Guo"
    homepage = "http://gizak.github.io"
