name = "Greyshade"
license = "MIT"
licenselink = "http://sm.mit-license.org/"
description = "Port of octopress's greyshade theme to Hugo"
homepage = "https://github.com/cxfksword/greyshade"
tags = ["blog", "octopress"]
features = ["blog"]
min_version = 0.14

[author]
  name = "cxfksword"
  homepage = "http://cxfksword.github.io"

# If porting an existing theme
[original]
  name = "Shashank Mehta"
  homepage = "http://github.com/shashankmehta/greyshade"
  repo = "https://github.com/shashankmehta/greyshade"
