baseurl = "http://hugo.spf13.com/"
title = "Hugo Themes"
author = "Steve Francia"
copyright = "Copyright (c) 2008 - 2014, Steve Francia; all rights reserved."
canonifyurls = true
paginate = 3

# Needed by Theme demos in exampleSite.
[params]
	DateForm = "Mon, Jan 2, 2006"
	headerimg = "toprow2.png"
	blogHeader = "<span style=\"font-size: 36px; \">Poop<b>Show</b></span>"
    tagline = "shows up next to your title"
    githubUrl = "your Github URL"
    contactEmail = "email address to use with the contact link"
    aboutLink = "relative path to your about page"
