# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Crisp"
license = "MIT"
licenselink = "https://github.com/Zenithar/hugo-theme-crisp/blob/master/LICENSE.md"
description = "Ghost crisp theme ported to Hugo"
homepage = "https://blog.zenithar.org/"
tags = ["ghost", "minimal"]
features = ["", ""]
min_version = 0.14

[author]
  name = "Thibault NORMAND"
  homepage = "http://zenithar.org"

# If porting an existing theme
[original]
  name = "Kathy Qian"
  homepage = "https://github.com/kathyqian"
  repo = "https://github.com/kathyqian/crisp-ghost-theme"
