name = "NeXT"
license = "MIT"
licenselink = "https://github.com/leopku/hugo-theme-next/blob/master/LICENSE"
description = "A very simple and fast theme for hugo,  which inspired by a hexo theme NexT"
homepage = "https://github.com/leopku/hugo-theme-next"
features = ["blog", "google analytics", "disqus"]
min_version = 0.14

[author]
  name = "leopku"
  homepage = "http://www.himysql.com"
